### PR TITLE
added failing test

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by damianh** [comment]
@jchannon Fixed it by reordering the MW https://github.com/damianh/OwinHttpMessageHandler/commit/4c4cdffdf10be66803cbb94b7133278770cd0e4d

**Comment by jchannon** [comment]
Thought you might. Now go see my repo and work out why it still fails :)

**Comment by damianh** [comment]
Which repo?

**Comment by jchannon** [comment]
https://github.com/jchannon/OwinCSRF

**Comment by jchannon** [comment]
Including @yantrio too

**Comment by damianh** [comment]
image

Test project is broken (clean clone)

**Comment by jchannon** [comment]
Thought that was fixed

**Comment by damianh** [comment]
cloned a third time, it compiles now wtf

**Comment by damianh** [comment]
see PR ;)

**Comment by jchannon** [comment]
Did you forget to push? :)

**Pull request merged**
